# Generated by Django 2.2 on 2023-03-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poker_board', '0004_auto_20230220_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timer', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker_board.PokerBoard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
