# Generated by Django 2.2 on 2023-02-17 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poker_board', '0002_auto_20230217_1751'),
        ('poker_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokergroupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pokergroupboard',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker_board.PokerBoard'),
        ),
        migrations.AddField(
            model_name='pokergroupboard',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker_group.PokerGroup'),
        ),
        migrations.AddField(
            model_name='pokergroup',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pokergroup',
            name='boards',
            field=models.ManyToManyField(related_name='poker_group_board', through='poker_group.PokerGroupBoard', to='poker_board.PokerBoard'),
        ),
        migrations.AddField(
            model_name='pokergroup',
            name='members',
            field=models.ManyToManyField(related_name='poker_group_user', through='poker_group.PokerGroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pokergroupmember',
            unique_together={('user', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='pokergroupboard',
            unique_together={('board', 'group')},
        ),
    ]
