# Generated by Django 2.2 on 2023-02-20 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_group', '0002_auto_20230217_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokergroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokergroup',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
