EXPIRY_TIME = 120
ACCOUNT_IS_CREATED = {'data': 'ACCOUNT IS CREATED SUCCESSFULLY'}  
USER_EXIST = {'data': 'ACCOUNT IS EXIST WITH THIS EMAIL ID'}  
LINK_IS_ALREADY_SEND = {'data': 'VERFICATION LINK IS ALREAY SEND ON EMAIL ID'}
LINK_SEND = {'data': 'VERFICATION LINK IS SEND ON YOUR EMAIL ID'}
LINK_EXPIRE = {'data': 'VERFICATION LINK IS EXPIRE'}
LINK_VERIFIED = {'data': 'ACCOUNT IS VERIFIED'}
