# Generated by Django 2.2 on 2023-02-20 11:41

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poker_board', '0002_auto_20230217_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokerboard',
            old_name='board_manager',
            new_name='manager',
        ),
        migrations.RemoveField(
            model_name='pokerboard',
            name='board_users',
        ),
        migrations.AddField(
            model_name='pokerboard',
            name='users',
            field=models.ManyToManyField(related_name='board', through='poker_board.PokerRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pokerboard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokerboard',
            name='estimation_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), size=8),
        ),
        migrations.AlterField(
            model_name='pokerboard',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='pokerboard',
            name='voting_system',
            field=models.IntegerField(choices=[(0, 'Fibonacci'), (1, 'Odd'), (2, 'Even'), (3, 'Serial')], default=0),
        ),
        migrations.AlterField(
            model_name='pokerrole',
            name='role',
            field=models.IntegerField(choices=[(0, 'Player'), (1, 'Spectator')], default=0),
        ),
    ]
