# Generated by Django 2.2 on 2023-03-02 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_board', '0004_auto_20230220_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerboard',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pokerboard',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='pokerboard',
            name='voting_system',
            field=models.IntegerField(choices=[(0, 'Fibonacci'), (1, 'Odd'), (2, 'Even'), (3, 'Serial'), (4, 'Custom')], default=0),
        ),
        migrations.AlterField(
            model_name='pokerrole',
            name='role',
            field=models.IntegerField(choices=[(0, 'Player'), (1, 'Spectator')], default=1),
        ),
    ]
