# Generated by Django 2.2 on 2023-02-20 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokeruser',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pokeruser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokeruser',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pokeruser',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pokeruser',
            name='email',
            field=models.EmailField(max_length=60, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='pokeruser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='pokeruser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
