# Generated by Django 2.2 on 2023-02-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokerTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_ticket_id', models.CharField(max_length=100, unique=True)),
                ('summary', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_estimated', models.BooleanField(blank=True, default=False, null=True)),
                ('final_estimation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PokerUserEstimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate', models.PositiveIntegerField(blank=True)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker_ticket.PokerTicket')),
            ],
        ),
    ]
