# Generated by Django 2.2 on 2023-02-17 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poker_board', '0002_auto_20230217_1751'),
        ('poker_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokeruserestimation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pokerticket',
            name='pokerboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker_board.PokerBoard'),
        ),
        migrations.AddField(
            model_name='pokerticket',
            name='user_estimation',
            field=models.ManyToManyField(related_name='poker_user_estimation', through='poker_ticket.PokerUserEstimation', to=settings.AUTH_USER_MODEL),
        ),
    ]
