# Generated by Django 2.2 on 2023-02-20 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poker_ticket', '0002_auto_20230217_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokerticket',
            old_name='jira_ticket_id',
            new_name='jira_ticket',
        ),
        migrations.RenameField(
            model_name='pokeruserestimation',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='pokeruserestimation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='pokerticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokerticket',
            name='pokerboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_ticket', to='poker_board.PokerBoard'),
        ),
        migrations.AlterField(
            model_name='pokerticket',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pokeruserestimation',
            unique_together={('user', 'ticket')},
        ),
    ]
