# Generated by Django 2.2 on 2023-02-20 11:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker_board', '0003_auto_20230220_1141'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poker_ticket', '0003_auto_20230220_1141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PokerTicket',
            new_name='Ticket',
        ),
    ]
