# Generated by Django 2.2 on 2023-02-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_ticket', '0004_auto_20230220_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokeruserestimation',
            name='estimate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
