# Generated by Django 2.2 on 2023-03-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_ticket', '0007_auto_20230221_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
